"""Add body column to Message

Revision ID: 83df936b5e16
Revises: 311d7246817d
Create Date: 2025-02-07 22:40:59.512953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83df936b5e16'
down_revision = '311d7246817d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
