"""Add created_at column to Message

Revision ID: 8695ca003b0f
Revises: f370555088fb
Create Date: 2025-02-07 22:45:36.181043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8695ca003b0f'
down_revision = 'f370555088fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'created_at')
    # ### end Alembic commands ###
